### ISSUE TITLE
Mirror Links

### ISSUE THREAD

**Issue by MrNooberDude** [Gzh0821/pvzg_site#11]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
School blocked the website lol
**Describe the solution you'd like**
Make a mirror link, maybe to your main website since all of pvzge.com is blocked
**Describe alternatives you've considered**
skill issue i guess
**Additional context**

**Comment by Gzh0821** [comment]
We are very sorry to hear this. 
We currently do not have any extra domains for deployment. 
You can try subdomains: [pvzge](https://www.pvzge.com) or try to use network proxy software to access.

**Comment by IceandFire04** [comment]
👍
