### ISSUE TITLE
Exe Version is slower than zip file version

### ISSUE THREAD

**Issue by kaisen7887** [Gzh0821/pvzg_site#7]
Hello it seems the loading using the .exe version in this game seems to be a lot slower than the regular zip file version especially on slower desktop platforms like laptops.

I know the importance of space saving but it will be nice if you can also include the zip file version if possible. Thank you very much.

**Comment by Gzh0821** [comment]
After our test, there is no obvious difference in loading speed between the new exe format and the old zip packaging method. This may be caused by the new version having more audio files and resource files.
